# Importing Modules

In [167]:
import numpy as np
import pandas as pd

# Importing the dataset

In [168]:
train = pd.read_csv('train.csv',index_col=0)
test = pd.read_csv('test.csv',index_col=0)

# Taking care of missing data

In [169]:
train.fillna({'Embarked':'S'},inplace=True)
test.fillna({'Embarked':'S'},inplace=True)
test.fillna({'Fare':0},inplace=True)

In [170]:
def age(data):
  age_ = data[0]
  class_ = data[1]
  if pd.isnull(age_):
    if class_ == 1:
      return 38
    elif class_ == 2:
      return 29
    else:
      return 24
  else:
    return age_

train['Age'] = train[['Age','Pclass']].apply(age,axis=1)
test['Age'] = test[['Age','Pclass']].apply(age,axis=1)

In [171]:
train.head()

Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S

[5 rows x 11 columns]

In [172]:
test.head()

Pclass  ... Embarked
PassengerId          ...         
892               3  ...        Q
893               3  ...        S
894               2  ...        Q
895               3  ...        S
896               3  ...        S

[5 rows x 10 columns]

# Encoding categorical data - Dependent Variable

In [173]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
train_ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,10])], remainder='passthrough')
test_ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,9])], remainder='passthrough')
train_dataset = np.array(train_ct.fit_transform(train))
test_dataset = np.array(test_ct.fit_transform(test))

# Data

In [174]:
train_dataset[0]

array([0.0, 1.0, 0.0, 0.0, 1.0, 0, 3, 'Braund, Mr. Owen Harris', 22.0, 1,
       0, 'A/5 21171', 7.25, nan], dtype=object)

In [175]:
test_dataset[0]

array([0.0, 1.0, 0.0, 1.0, 0.0, 3, 'Kelly, Mr. James', 34.5, 0, 0,
       '330911', 7.8292, nan], dtype=object)

# Splitting the dataset into the Training set and Test set

In [176]:
X_train = train_dataset[:, [0,1,2,3,4,6,8,9,10,12]]
X_test = test_dataset[:, [0,1,2,3,4,5,7,8,9,11]]
y_train = train_dataset[:, 5]
y_train = y_train.astype('int')

In [177]:
X_train[0]

array([0.0, 1.0, 0.0, 0.0, 1.0, 3, 22.0, 1, 0, 7.25], dtype=object)

In [178]:
X_test[0]

array([0.0, 1.0, 0.0, 1.0, 0.0, 3, 34.5, 0, 0, 7.8292], dtype=object)

In [179]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

# Training the Random Forest Classification model on the Training set

In [180]:
from sklearn.ensemble import RandomForestClassifier
csf = RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
csf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

# Predicting the Test set results

In [181]:
y_pred = csf.predict(X_test)

# Export into CSV

In [183]:
output = pd.DataFrame({'PassengerId' : test.index, 'Survived' : y_pred})
output.to_csv('my_submission.csv',index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
